plugins:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  Exclude:
  - 'lib/generators/templates/**/*'
  - 'spec/dummy/**/*'
  - 'vendor/**/*'

Layout/LineLength:
  Max: 140

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 25

Metrics/ModuleLength:
  Max: 250

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Style/Documentation:
  Enabled: false

Naming/PredicateName:
  Enabled: false
