sudo: false
language: ruby
rvm:
- 2.2.4
before_install: gem install bundler -v 1.12.5
deploy:
  provider: rubygems
  api_key:
    secure: G4d4fEwMC+28+npndYC4ykpRVCgsv7W9CCHA+Zp1SjIVY8L6vCBvIBD6hXAbMytKuPxEEysyNVvtK4Cfd2HarwLIhnBbcE1cBVYvrN3BUT/2NfNfmCDSP4ldh4lnZwULZeMyEJwVQzMlDfy5B3F7CAz7D3utp185sKBzZbKCFHCv5ufyt81uLOdOIQGWAmAJ6WaS+o7UwVYMJ/2pbdtwIbVdBl/S4vMqrK+AkP4QCATCU66AJoot0x6ClK5Fi/R/UVHa1KMG6tlL8OCvaSOnjg1MjsFCaa0ttC5YPM7kpKeHCkzn9cO/+v7pFXdxAPByxN8QGOHRJw6CPbg7VZh/EqObYCPEhhu/MlBuyBbsZrMB8ylFkPGobL3FZBIK9d0YfThk43r2zUnzhpGuTp0mRqUiAI0sx8xtbs1QOwKkAJmoPgyOLDCbUPR/MLUgdzvNy7BDd5WIM2bjE+BXP5GtigyztiynxUcoATtDoaeY/KQ92tWYSEAc2DC7ggb1GYbMyGZFjRVvqTl/kI4fUtqZft8XoMAXYQPxIikEYfH9Hg9WhDGCXi2GEF9s6nOfhgOcUEAJyMm9Oh4qUQr9UXOppfgEW0AFDUjLuoyx6de6v/cg736VQho2Ex1UF1ol1aXCBdmfjVH6njEeheWaxE9M1+32/TdvK5knE49ZrHrxeiU=
  gem: external_services
  on:
    tags: true
    repo: flant/external_services
